name: Pull request CI build

on:
  workflow_dispatch:

jobs:
  docker_build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push GUACD Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: cyolosec/guacd:multi
          platforms: linux/amd64,linux/arm64
          push: true